name: TeamCity Tests

on: push

jobs:
  run_teamcity_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install ifconfig
        run: sudo apt-get update && sudo apt-get install -y net-tools

      - name: Setup host environment variables
        run: |
          echo "HOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)" >> $GITHUB_ENV

      - name: Setup host config.properties
        run: echo "host=$HOST:8111" > src/main/resources/config.properties

      - name: Pull Selenoid Chrome
        run: docker pull selenoid/vnc_chrome:119.0

      - name: Pull Selenoid Firefox
        run: docker pull selenoid/vnc:firefox_89.0

      - name: Run Selenoid
        run: |
          docker run -d \
            --name selenoid \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/config/:/etc/selenoid/:ro \
            aerokube/selenoid

      - name: Run Selenoid UI
        run: |
          docker run -d --name selenoid-ui \
          -p 8080:8080 \
          aerokube/selenoid-ui \
          --selenoid-uri http://$HOST:4444

      - name: Run TeamCity Server
        run: |
          docker run -u 0 -d --name teamcity-server \
          -v $(pwd)/tmp/teamcity_server/datadir:/data/teamcity_server/datadir \
          -v $(pwd)/tmp/teamcity_server/logs:/opt/teamcity/logs \
          -p 8111:8111 \
          jetbrains/teamcity-server:latest

      - name: Set up superUserToken environment variable
        run: echo "SUPER_USER_TOKEN=$(docker logs teamcity-server | grep 'Super user authentication token' | tail -n 1 | awk '{print \$6}')" >> $GITHUB_ENV

      - name: Set up config property
#        run: echo "\nsuperUserToken=$SUPER_USER_TOKEN" >> src/main/resources/config.properties
        run: echo "\nsuperUserToken=$SUPER_USER_TOKEN\nremote=true\nbrowser=firefox" >> src/main/resources/config.properties

      - name: Verify config.properties
        run: cat src/main/resources/config.properties

      - name: Setup TeamCity Server
        run: ./mvnw clean test -Dtest=SetupTest#setupTeamCityServerTest

      - name: Run TeamCity agent
        run: |
          docker run -e SERVER_URL=http://$HOST:8111 -u 0 -d --name teamcity-agent \
          -v $(pwd)/tmp/teamcity_agent/conf:/data/teamcity_agent/conf \
          jetbrains/teamcity-agent:latest

      - name: Set up TeamCity agent
        run: ./mvnw test -Dtest=SetupFirstStartTest#setupTeamCityAgentTest

      - name: Run tests
        run: ./mvnw test -Dgroups=Regression


          


